# For the love of god use C-a
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Just easier to nagivate
set -g base-index 1

set -sg escape-time 1

setw -g mode-keys vi
set-option -gq mouse on
