with-fingerprint
no-emit-version
charset utf-8
keyid-format 0xlong

# Passphrase
s2k-cipher-algo AES256
s2k-digest-algo SHA512
s2k-mode 3
s2k-count 65011812

# Asymmetric
personal-digest-preferences SHA512 SHA256
personal-cipher-preferences AES256
personal-compress-preferences Uncompressed
