# vim: set ft=config:
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
use-damage = true;

shadow = false;
fading = false;
inactive-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
daemon = true
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
detect-transient = true;
detect-client-leader = true;

vsync = true;
