[alias]
a   = "audit"
b   = "build"
bb  = "build --release"
c   = "clippy"
d   = "doc"
dd  = "doc --release"
do  = "doc --open"
ddo = "doc --release --open"
o   = "outdated"
r   = "run"
rr  = "run --release"
t   = "nextest run"
u   = "update"

[registries.crates-io]
protocol = "sparse"
